#!/bin/sh

monitor_text=$(niri msg -j outputs)
# monitor_width=$(awk '/Logical size:/ { split($3, dims, "x"); print dims[1]; exit }' <<< $monitor_text)
# monitor_height=$(awk '/Logical size:/ { split($3, dims, "x"); print dims[2]; exit }' <<< $monitor_text)
monitor_id=$(jq 'keys_unsorted[0]' <<< $monitor_text)
monitor_width=$(jq ".$monitor_id.logical.width" <<< $monitor_text)
monitor_height=$(jq ".$monitor_id.logical.height" <<< $monitor_text)
# echo $monitor_width
# echo $monitor_height


window_obj=$(niri msg -j windows | jq ". | map(select(.title | contains(\"$2\")))" | jq '.[0]')

window_id=$(jq '.id' <<< $window_obj)
window_title=$(jq '.title' <<< $window_obj)
window_float=$(jq '.is_floating' <<< $window_obj)
if [[ "$window_float" == "false" ]]; then
  # echo "Window is not floating"
  niri msg action toggle-window-floating --id $window_id
  niri msg action set-window-width 480 --id $window_id
  niri msg action set-window-height 270 --id $window_id
fi

window_width=$(jq '.layout.window_size.[0]' <<< $window_obj)
window_height=$(jq '.layout.window_size.[1]' <<< $window_obj)

if [[ "$1" == "show" ]]; then
  window_x=$(jq '.layout.tile_pos_in_workspace_view.[0]' <<< $window_obj)
  window_y=$(jq '.layout.tile_pos_in_workspace_view.[1]' <<< $window_obj)
  window_x=$(awk '{print int($1)}' <<< $window_x)
  window_y=$(awk '{print int($1)}' <<< $window_y)
  # echo $window_x
  # echo $((monitor_width - window_width))
  if [[ $window_x -lt $((monitor_width - window_width)) ]]; then
    niri msg action move-floating-window -x $monitor_width -y $((monitor_height - window_height - 50)) --id $window_id
  else
    niri msg action move-floating-window -x $((monitor_width - window_width - 100)) -y $((monitor_height - window_height - 50)) --id $window_id
  fi
elif [[ "$1" == "sticky" ]]; then
  nsticky sticky toggle-appid $window_id
else
  echo "Please use either arguments show or sticky"
fi


# echo $window_obj | jq .
